LAND_USE_IDS = {
    1110: "Producción agrícola comercial",
    1120: "Infraestructuras agrícolas",
    1200: "Silvicultura",
    1300: "Industrias extractivas",
    1310: "Extracción de materiales productores de energía",
    1320: "Extracción de minerales metálicos",
    1330: "Otras industrias extractivas (minas, canteras y graveras)",
    1410: "Acuicultura",
    1420: "Pesca",
    1500: "Otras actividades primarias",
    1600: "Dehesa",
    2000: "Producción secundaria",
    2110: "Fabricación de productos textiles",
    2120: "Fabricación de madera y productos basados en la madera",
    2130: "Fabricación de pasta papelera y de papel",
    2140: "Fabricación de coque y productos refinados de petróleo y de combustible nuclear",
    2150: "Fabricación de sustancias químicas, productos químicos y fibras artificiales",
    2160: "Fabricación de metales básicos y metalurgia",
    2170: "Fabricación de productos minerales no metálicos",
    2180: "Fabricación de productos de caucho y de plástico",
    2190: "Fabricación de otras materias primas",
    2210: "Fabricación de maquinaria",
    2220: "Fabricación de vehículos y medios de transporte",
    2230: "Fabricación de otros productos finales pesados",
    2310: "Elaboración de alimentos, bebidas y productos de tabaco",
    2320: "Elaboración de productos de ropa y cuero",
    2330: "Edición e impresión",
    2340: "Fabricación de aparatos eléctricos y ópticos",
    2350: "Fabricación de otros productos finales ligeros",
    2400: "Producción de energía",
    2410: "Producción de energía nuclear",
    2420: "Producción de energía basada en combustibles fósiles",
    2430: "Producción de bionergía",
    2441: "Eólica",
    2442: "Solar",
    2443: "Hidroeléctrica",
    2444: "Otras energías renovables",
    2500: "Otros sectores de la industria",
    3110: "Comercio mayorista y minorista, reparación de vehículos y de efectos personales y enseres domésticos",
    3120: "Servicios inmobiliarios",
    3131: "Alojamiento",
    3132: "Restauración",
    3133: "Camping",
    3140: "Otros servicios comerciales",
    3210: "Servicios financieros y de seguros",
    3220: "Servicios profesionales, técnicos y científicos",
    3230: "Servicios de información y comunicación",
    3240: "Servicios administrativos y de asistencia",
    3250: "Otros servicios financieros, profesionales y de información",
    3310: "Servicios de administración pública, de defensa y de seguridad social",
    3311: "Penitenciario",
    3320: "Servicios de educación",
    3330: "Servicios sanitarios y sociales",
    3340: "Servicios religiosos",
    3350: "Otros servicios a la comunidad",
    3351: "Cementerio",
    3410: "Servicios culturales",
    3421: "Parque recreativo",
    3422: "Ocio",
    3431: "Campo de golf",
    3432: "Instalaciones deportivas",
    3441: "Parque urbano",
    3442: "Zonas recreativas",
    3450: "Otras actividades recreativas",
    3500: "Otras actividades del sector terciario",
    4111: "Vías",
    4112: "Áreas de estacionamiento",
    4113: "Estaciones y áreas de servicio e infraestructuras",
    4121: "Vías de ferrocarril",
    4122: "Infraestructuras ferroviarias",
    4130: "Transporte aéreo",
    4140: "Transporte marítimo y por vías navegables interiores",
    4150: "Otras redes de transporte",
    4200: "Servicios logísticos y de almacenamiento",
    4310: "Servicios de distribución de energía eléctrica, gas y energía térmica",
    4321: "Depuradoras y potabilizadoras",
    4322: "Desalinizadoras",
    4331: "Vertederos y escombreras",
    4332: "Plantas de tratamiento",
    4340: "Otros servicios básicos de abastecimiento y gestión de residuos",
    5000: "Uso residencial",
    6100: "Áreas transitorias",
    6200: "Áreas abandonadas",
    6310: "Áreas naturales terrestres",
    6320: "Áreas de agua",
    6600: "Uso desconocido",
}
