# Logging settings
logging.level = 'INFO'

processed_data_folder = '/data/processed'
results_folder = '/data/results'

[geodata]
saving_format = 'geojson'

[data]
saving_format = 'csv'

[pv_coverage]
# Potencia por hectarea en kW/Ha
power_per_ha_roof = 50
power_per_ha_floor = 500
# Horas estimadas de funcionamiento al año
hef_roof = 1300
hef_floor = 1650
# Porcentaje de consumo a cubrir, entre 0 y 1
consumption_to_cover = 0.5

# Rename of the column to handle it better
[pv_coverage.column_rename]
"municipio" = "municipio"
"km2" = "superficie_km2"
"nº habitantes" = "population"
"Consumo anual electricidad - media 2014-2019 (MWh)" = "mean_electricity_consumption"
"Sup. urbana (Ha)" = "urban_ha"
"Sup. rústica (Ha)" = "rural_ha"

[land_use]
urbanized_zones = [
    # Industrial zones
    2000, 2110, 2120, 2130, 2140, 2150, 2160, 2170, 2180, 2190, 2210, 2220,
    2230, 2310, 2320, 2330, 2340, 2350, 2500,
    # Service zones
    3110, 3120, 3131, 3132, 3140, 3210, 3220, 3230, 3240, 3250, 3310, 3311,
    3320, 3330, 3340, 3350, 3410, 3421, 3432, 3500, 4200,
    # Urban zones
    5000, 6100, 6200, 6600,
    # Infraestructure
    4112, 4113
]
industrial_zones = [
    2000, 2110, 2120, 2130, 2140, 2150, 2160, 2170, 2180, 2190, 2210, 2220,
    2230, 2310, 2320, 2330, 2340, 2350, 2500
]
urban_zones = [
    5000, 6100, 6200, 6600
]
service_zones = [
    3110, 3120, 3131, 3132, 3140, 3210, 3220, 3230, 3240, 3250, 3310, 3311,
    3320, 3330, 3340, 3350, 3410, 3421, 3432, 3500, 4200
]

[ree]
max_days_per_request = 15

[ree.generation_mapping]
"dem" = "Demanda"
"eol" = "Eólica"
"nuc" = "Nuclear"
"car" = "Carbón"
"cc" = "Ciclo combinado"
"hid" = "Hidráulica"
"inter" = "Intercambios int"
"solFot" = "Solar fotovoltaica"
"solTer" = "Solar térmica"
"termRenov" = "Térmica renovable"
"die" = "Motores diésel"
"gas" = "Turbina de gas"
"vap" = "Turbina de vapor"
"genAux" = "Generación auxiliar"
"cogenResto" = "Cogeneración y residuos"
